### PR TITLE
.Net core porting - GVFS.FunctionalTests.LockHolder

### LINKED ISSUE #701: Mac: Detection of dead git processes (during lock acquire\release) does not work
```
~/BugBashRepos/Office.Prototype/src>git checkout - .
^C
~/BugBashRepos/Office.Prototype/src>git checkout -- .
Waiting for 'git checkout - .' to release the lock.../
```

I confirmed that that the ^C did kill the git process.

### PR DESCRIPTION
**Pull request by alameenshah**
Porting FunctionalTests.LockHolder to .netcore
- Migrated the project file to new format 
- Removed GVFS.Platform.Windows dependency 
- Directly using WindowsFileSystem.Shared.cs 
- Updated GitHelper to launch GVFS.FunctionalTests.LockHolder.dll using dotnet command. Previously it was an exe and launched directly 
- Replaced WindowsPlatform code (GVFSPlatform.Instance.GetNamedPipeName) with private implementation 
- Removed Categories.MacTODO.NeedsLockHolder 7.Implemented IsProcessActiveImplementation on MacPlatform.

Fixes #701, #150

### CODE REVIEW

**Comment by wilbaker** [comment]
@alameenshah can you also try removing `NeedsLockHolder` from `Categories.MacTODO` (and all of the code that uses it)?

The tests that require the LockHolder should pass on Mac.  If they're failing, we'll need a new MacTODO category and work item to track fixing the test(s).  

If the failures are something minor, e.g. using Windows paths instead of `Path.Combine` you might as well fix them now.

**Comment by wilbaker** [comment]
Resolves #150

File: GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs [hunk 1]
```diff
@@ -45,6 +41,45 @@ public void Execute()
...
 
+        private static bool TryGetGVFSEnlistmentRootImplementation(string directory, out string enlistmentRoot, out string errorMessage)
+        {
+            if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
+            {
+                return MacPlatform.TryGetGVFSEnlistmentRootImplementation(directory, out enlistmentRoot, out errorMessage);
+            }
+            else
+            {
+                enlistmentRoot = null;
```
Comment (alameenshah) [inline GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs]: Not able to use WindowsPlatform here - because of its dependency on WindowsIdentity. Let me know if there is a better approach.

File: GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs [hunk 2]
```diff
@@ -45,6 +41,45 @@ public void Execute()
...
+
+        private static string GetNamedPipeNameImplementation(string enlistmentRoot)
+        {
+            if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
+            {
+                return MacPlatform.GetNamedPipeNameImplementation(enlistmentRoot);
+            }
+            else
+            {
+                return "GVFS_" + enlistmentRoot.ToUpper().Replace(':', '_');
```
Comment (alameenshah) [inline GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs]: Not able to use WindowsPlatform here - because of its dependency on WindowsIdentity (and also kernel32.dll). Let me know if there is an alternate approach.

File: Scripts/Mac/CleanupFunctionalTests.sh [hunk 3]
```diff
@@ -3,6 +3,7 @@
 pkill -9 -l GVFS.FunctionalTests
 pkill -9 -l git
 pkill -9 -l gvfs
+pkill -9 -l GVFS.Mount
```
Comment (alameenshah) [inline Scripts/Mac/CleanupFunctionalTests.sh]: This is an unrelated change - Functional tests were failing when a previous test was cancelled.

File: GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs (hunk 1 above)
Comment (wilbaker) [reply GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs]: The only alternative that jumps out to me is moving `TryGetGVFSEnlistmentRootImplementation` and `GetNamedPipeNameImplementation` into a new `WindowsPlatform.Shared.NetStandard.cs` file that has only code that can compile into .NET Standard.

With how limited this is though I think you'd be OK just adding a comment here that describes why the code was copied rather than calling `WindowsPlatform`.  As general rule the functional test code doesn't consume product code anyway, this project is the one exception.

Comment (wilbaker) [reply GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs]: Once everything moves to .NET Core for the WindowsIdentity issue we can look at the compatibility pack described here: https://devblogs.microsoft.com/dotnet/announcing-the-windows-compatibility-pack-for-net-core/

File: GVFS/GVFS.FunctionalTests.LockHolder/GVFS.FunctionalTests.LockHolder.csproj [hunk 4]
```diff
@@ -1,87 +1,42 @@
...
+﻿<Project Sdk="Microsoft.NET.Sdk">
+  <Import Project="..\GVFS.Build\GVFS.cs.props" />
   <PropertyGroup>
-    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
-    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
-    <ProjectGuid>{FA273F69-5762-43D8-AEA1-B4F08090D624}</ProjectGuid>
     <OutputType>Exe</OutputType>
+    <TargetFramework>netcoreapp2.1</TargetFramework>
+    <Platforms>x64</Platforms>
+	<!-- see https://github.com/NuGet/Home/issues/4837 for reference to CopyLocalLockFileAssemblies -->
```
Comment (nickgra) [inline GVFS/GVFS.FunctionalTests.LockHolder/GVFS.FunctionalTests.LockHolder.csproj]: nit: ws around the comment

File: GVFS/GVFS.FunctionalTests.LockHolder/GVFS.FunctionalTests.LockHolder.csproj [hunk 5]
```diff
@@ -1,87 +1,42 @@
...
     <RootNamespace>GVFS.FunctionalTests.LockHolder</RootNamespace>
     <AssemblyName>GVFS.FunctionalTests.LockHolder</AssemblyName>
-    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
-    <FileAlignment>512</FileAlignment>
-    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
-    <NuGetPackageImportStamp>
-    </NuGetPackageImportStamp>
   </PropertyGroup>
+
   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
```
Comment (nickgra) [inline GVFS/GVFS.FunctionalTests.LockHolder/GVFS.FunctionalTests.LockHolder.csproj]: Can we keep the spacing consistent in the PropertyGroups for all of our SDK style projects? VSMac has been sensitive to this in the past.
GVFS.Common has
`  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">`

File: GVFS/GVFS.FunctionalTests.LockHolder/GVFS.FunctionalTests.LockHolder.csproj [hunk 6]
```diff
@@ -1,87 +1,42 @@
...
-    <ProjectReference Include="..\GVFS.Platform.Windows\GVFS.Platform.Windows.csproj">
-      <Project>{4CE404E7-D3FC-471C-993C-64615861EA63}</Project>
-      <Name>GVFS.Platform.Windows</Name>
-    </ProjectReference>
-    <ProjectReference Include="..\GVFS.Virtualization\GVFS.Virtualization.csproj">
-      <Project>{f468b05a-95e5-46bc-8c67-b80a78527b7d}</Project>
-      <Name>GVFS.Virtualization</Name>
-    </ProjectReference>
+    <ProjectReference Include="..\GVFS.Common\GVFS.Common.csproj" />
+	<ProjectReference Include="..\GVFS.Virtualization\GVFS.Virtualization.csproj" />
```
Comment (nickgra) [inline GVFS/GVFS.FunctionalTests.LockHolder/GVFS.FunctionalTests.LockHolder.csproj]: ws on this line

File: GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs [hunk 7]
```diff
@@ -27,7 +28,19 @@ private static string LockHolderCommandPath
         {
             get
             {
-                return Path.Combine(Settings.Default.CurrentDirectory, LockHolderCommand);
+                if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
```
Comment (nickgra) [inline GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs]: Can you leave a comment here about why we need this change? (the differences between Windows and Mac and how we run the functional tests)

File: GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs (hunk 1 above)
Comment (nickgra) [reply GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs]: I agree with William; let's leave a comment here on why we're doing it this way (and that we're intentionally duplicating code). Probably best to leave this comment as a TODO(Mac) so we'll find it whenever we end up moving everything to .NET Core.

File: GVFS/GVFS.Platform.Mac/MacPlatform.Shared.cs [hunk 8]
```diff
@@ -15,7 +17,19 @@ public static bool IsElevatedImplementation()
...
-            // TODO(Mac): Implement proper check
+            try
+            {
+                Process process = Process.GetProcessById(processId);
+            }
+            catch (ArgumentException)
+            {
+                return false;
+            }
+            catch (InvalidOperationException)
```
Comment (wilbaker) [inline GVFS/GVFS.Platform.Mac/MacPlatform.Shared.cs]: Minor: On the Windows platform we [don't catch](https://github.com/Microsoft/VFSForGit/blob/6dca004e2361927f96f2ebdbff3c351b4695bd38/GVFS/GVFS.Platform.Windows/WindowsPlatform.Shared.cs#L61) `InvalidOperationException`, and I am guessing because this appears to be [a bug in the documentation](https://stackoverflow.com/questions/52519030/net-getprocessbyid-when-is-invalidoperationexception-thrown).

As best I can tell this won't get thrown in [the .NET Core version on Mac](https://github.com/dotnet/corefx/blob/71122bb4921e0239ea679dd275d53695b94e52f4/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L998) either, and so I don't think we need to catch it here.

Comment (wilbaker) [reply GVFS/GVFS.Platform.Mac/MacPlatform.Shared.cs]: (If you'd prefer to match the docs I recommend updating the Windows code to match instead)

File: GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs [hunk 9]
```diff
@@ -45,6 +41,45 @@ public void Execute()
             }
         }
 
+        private static bool TryGetGVFSEnlistmentRootImplementation(string directory, out string enlistmentRoot, out string errorMessage)
+        {
+            if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
+            {
+                return MacPlatform.TryGetGVFSEnlistmentRootImplementation(directory, out enlistmentRoot, out errorMessage);
+            }
+            else
```
Comment (wilbaker) [inline GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs]: Minor: There's no need for this `else` because of the earlier `return`.

File: GVFS/GVFS.Platform.Mac/MacPlatform.Shared.cs (hunk 8 above)
Comment (alameenshah) [reply GVFS/GVFS.Platform.Mac/MacPlatform.Shared.cs]: removed the un-necessary catch

File: GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs [hunk 10]
```diff
@@ -45,6 +41,43 @@ public void Execute()
...
+
+        private static string GetNamedPipeNameImplementation(string enlistmentRoot)
+        {
+            if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
+            {
+                return MacPlatform.GetNamedPipeNameImplementation(enlistmentRoot);
+            }
+
+            // Not able to use WindowsPlatform here - because of its dependency on WindowsIdentity (and also kernel32.dll).
+            return "GVFS_" + enlistmentRoot.ToUpper().Replace(':', '_');
```
Comment (kewillford) [inline GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs]: There is now code that we have to keep in sync.  Add a comment here pointing to the code in `WindowsPlatform`  and a comment in `WindowsPlatform` pointing to this code so that if we ever change one we will know to change the other.

File: GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs [hunk 11]
```diff
@@ -18,7 +19,7 @@ public static class GitHelpers
         /// GVFS.FunctionalTests.LockHolder program.
         /// </summary>
         private const string LockHolderCommandName = @"GVFS.FunctionalTests.LockHolder";
-        private const string LockHolderCommand = @"GVFS.FunctionalTests.LockHolder.exe";
+        private const string LockHolderCommand = @"GVFS.FunctionalTests.LockHolder.dll";
```
Comment (kewillford) [inline GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs]: Aren't we going to run a `dotnet publish` for this which will make it a `.exe` on Windows and no extension on Mac?

File: GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs [hunk 12]
```diff
@@ -126,7 +145,20 @@ public static void CheckGitCommandAgainstGVFSRepo(string virtualRepoRoot, string
...
+            string args = LockHolderCommandPath;
+            if (skipReleaseLock)
+            {
+                args += " --skip-release-lock";
+            }
+
+            return RunCommandWithWaitAndStdIn(
+                enlistment,
+                resetTimeout,
+                "dotnet",
```
Comment (kewillford) [inline GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs]: So we are running the `dotnet` command and passing the lock holder as an arg?  Why can't we just run the lockholder?

File: GVFS/GVFS.Platform.Mac/MacPlatform.Shared.cs [hunk 13]
```diff
@@ -15,7 +17,15 @@ public static bool IsElevatedImplementation()
 
         public static bool IsProcessActiveImplementation(int processId)
         {
-            // TODO(Mac): Implement proper check
+            try
+            {
+                Process process = Process.GetProcessById(processId);
```
Comment (kewillford) [inline GVFS/GVFS.Platform.Mac/MacPlatform.Shared.cs]: Do we need to check that the `process` is not null or match the processId that we passed in?  Is an exception the only indication that the process is not active?

File: GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs (hunk 11 above)
Comment (wilbaker) [reply GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs]: (I'l jump in here since this was my recommendation in offline discussions with @alameenshah)

The Windows build does not currently have a `dotnet publish` step, and so it was simpler to have the tests call `dotnet` for the lock holder (like we do for the [unit tests](https://github.com/Microsoft/VFSForGit/blob/8c8927ff421d8181a12b7c53de76c1defd80092c/Scripts/RunUnitTests.bat#L9) and [functional tests](https://github.com/Microsoft/VFSForGit/blob/8c8927ff421d8181a12b7c53de76c1defd80092c/Scripts/RunFunctionalTests.bat#L42) on Windows).

We *do* have a publish step on Mac (and could launch the lock holder there without `dotnet`) but we can reduce the amount of Mac and Windows specific code by using `dotnet` on both.

CC: @nickgra for his thoughts on this approach

File: GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs (hunk 12 above)
Comment (wilbaker) [reply GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs]: This is because of the conversation in the other comment, Windows does not have a `dotnet publish` step.

File: GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs (hunk 10 above)
Comment (alameenshah) [reply GVFS/GVFS.FunctionalTests.LockHolder/AcquireGVFSLock.cs]: Agree. We discussed this - please see @wilbaker's comments above. 

(With how limited this is though I think you'd be OK just adding a comment here that describes why the code was copied rather than calling WindowsPlatform. As general rule the functional test code doesn't consume product code anyway, this project is the one exception.

Once everything moves to .NET Core for the WindowsIdentity issue we can look at the compatibility pack described here: https://devblogs.microsoft.com/dotnet/announcing-the-windows-compatibility-pack-for-net-core/)

File: GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs (hunk 11 above)
Comment (alameenshah) [reply GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs]: the extension would be `.dll` on both Mac and Windows. Even after Publish.

Comment (kewillford) [reply GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs]: Are there any gotchas or potential differences in running one way or the other?

File: GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs (hunk 12 above)
Comment (alameenshah) [reply GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs]: after the migration to .netcore, the extension now is `.dll` and became easier to launch it using `dotnet`

File: GVFS/GVFS.Platform.Mac/MacPlatform.Shared.cs (hunk 13 above)
Comment (alameenshah) [reply GVFS/GVFS.Platform.Mac/MacPlatform.Shared.cs]: No need to check `process`. We already follow this pattern in  `WindowsPlatform.Shared::IsProcessActiveImplementation` and also in `GitReadAndGitLockTests::OrphanedGVFSLockIsCleanedUp()`)

File: GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs (hunk 11 above)
Comment (nickgra) [reply GVFS/GVFS.FunctionalTests/Tools/GitHelpers.cs]: In my mind, the risk of running the publish binaries has always been that if you're iterating in the IDE on some changes, you're only updating the BuildOutput version of the binaries, not the ones that live in Publish. We could publish as part of every build, but that'd slow down our inner loop.

Maybe that's a risk that is imagined, but I can see myself making that mistake at least :)
