### PR TITLE
When using --set add folders back to directories for checking git status

### LINKED ISSUE #1460: Gvfs sparse -a fails with "dirty" git status even if "dirty" files are within sparse list
I’ve confirmed that gvfs sparse -a seems to fail whenever your repo is dirty at all, regardless of whether or not the added/edited files are in your sparse list at all. I realize the decision to fail if the repo is dirty at all opens up some weird edge cases, however I think it is way too brittle, especially since we are talking about having tooling (git hooks and scoper) call gvfs sparse unbeknownst to the user. Would a better approach be to only fail gvfs sparse if there are dirty folders present that are outside of the sparse list you are switching to?

### PR DESCRIPTION
**Pull request by kewillford**
The set option was removing folder from the directories hashset to know
what folders needed to be removed but the directories hashset was used
in checking status and for pruning so it needs to be the set of folders
that will be in the sparse set after determining the what to add and remove
so that git status and prune will have the correct set of sparse folders.

Fixes #1460

### CODE REVIEW

File: GVFS/GVFS/CommandLine/SparseVerb.cs [hunk 1]
```diff
@@ -166,6 +166,13 @@ protected override void Execute(GVFSEnlistment enlistment)
                         {
                             needToChangeProjection = true;
                             foldersToRemove.AddRange(directories);
+                            directories.Clear();
+                        }
+
+                        // Need to add folders that will be in the projection back into directories for the status check
+                        foreach (string folder in foldersToAdd)
+                        {
+                            directories.Add(folder);
```
Comment (wilbaker) [inline GVFS/GVFS/CommandLine/SparseVerb.cs]: Do we also need to add pack in directories that were in the set before the command was run?

Consider this scenario:

- InitialSet: { A, B, C }
- `set` is called with { B, C, D }

`foldersToRemove ` will be { A } and `foldersToAdd` will be { D } meaning that after this loop `directories` will only have { D }, when it should be { B, C, D }.

Rather than re-adding `foldersToAdd` should we be re-adding `folders`?

If there's not already it might be worth adding a test that would catch this.

Comment (wilbaker) [reply GVFS/GVFS/CommandLine/SparseVerb.cs]: To clarify, I think the problem would be if something was modified in { B, C } git status would flag it when it probably shouldn't.

Comment (kewillford) [reply GVFS/GVFS/CommandLine/SparseVerb.cs]: I will add a test case for this.
