### PR TITLE
Windows: Add delay and retry to attributes check in ExpandedFileAttributesAreUpdated

### LINKED ISSUE #348: Add retry logic to BasicFileSystemTests.ExpandedFileAttributesAreUpdated test
Sometimes `ExpandedFileAttributesAreUpdated` fails because the following attributes are also set:

```
#define FILE_ATTRIBUTE_SPARSE_FILE          0x00000200  // winnt
#define FILE_ATTRIBUTE_REPARSE_POINT        0x00000400  // winnt 
#define FILE_ATTRIBUTE_RECALL_ON_OPEN       0x00040000  // winnt 
```

Per the ProjFS team there is currently a race where these still might be set on the file after it's expanded to full.  Rather than failing immediately, the test should have retry\sleep logic when checking the file attributes.

### PR DESCRIPTION
**Pull request by wilbaker**
Fixes #348.

Added sleep\retry logic to `ExpandedFileAttributesAreUpdated` because the ProjFS related attributes are not removed synchronously when a file is converted to full.

### CODE REVIEW

File: GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/BasicFileSystemTests.cs [hunk 1]
```diff
@@ -8,12 +8,17 @@
...
+using System.Threading;
 
 namespace GVFS.FunctionalTests.Tests.LongRunningEnlistment
 {
     [TestFixture]
     public class BasicFileSystemTests : TestsWithEnlistmentPerFixture
     {
+        private const int FileAttributeSparseFile = 0x00000200;
+        private const int FileAttributeReparsePoint = 0x00000400;
+        private const int FileAttributeRecallOnOpen = 0x00040000;
```
Comment (jrbriggs) [inline GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/BasicFileSystemTests.cs]: As per Abhijeet's email, should this be `FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS` (`0x00400000`) ?

Comment (wilbaker) [reply GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/BasicFileSystemTests.cs]: Yep thanks!
