### PR TITLE
[upgrade] Upgrade Functional Test failure fix

### LINKED ISSUE #852: NoReminderForLeftOverDownloads test occasionally fails
```
Errors, Failures and Warnings

1) Failed : GVFS.FunctionalTests.Tests.EnlistmentPerFixture.UpgradeReminderTests.NoReminderForLeftOverDownloads()
  Expected: False
  But was:  True
   at GVFS.Tests.Should.ValueShouldExtensions.ShouldEqual[T](T actualValue, T expectedValue, String message) in C:\agent\_work\10\s\GVFS\GVFS.Tests\Should\ValueShouldExtensions.cs:line 34
   at GVFS.Tests.Should.ValueShouldExtensions.ShouldBeFalse(Boolean actualValue, String message) in C:\agent\_work\10\s\GVFS\GVFS.Tests\Should\ValueShouldExtensions.cs:line 16
   at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.UpgradeReminderTests.VerifyServiceRestartStopsReminder() in C:\agent\_work\10\s\GVFS\GVFS.FunctionalTests\Tests\EnlistmentPerFixture\GVFSUpgradeReminderTests.cs:line 149
   at GVFS.FunctionalTests.Tests.EnlistmentPerFixture.UpgradeReminderTests.NoReminderForLeftOverDownloads() in C:\agent\_work\10\s\GVFS\GVFS.FunctionalTests\Tests\EnlistmentPerFixture\GVFSUpgradeReminderTests.cs:line 61
```

https://gvfs.visualstudio.com/ci/_build/results?buildId=7376

I marked this build run as retained.

### PR DESCRIPTION
**Pull request by alameenshah**
When Nuget settings (`upgrade.feedurl` & `upgrade.feedpackagename`) are not available in `gvfs config`, then an attempt to read (or write) those missing values will cause `gvfs config read/write` to exit with error code `3`. `UpgradeReminder` FT tries to 1. read existing nuget config, 2. delete it, 3. execute tests and then 4. restore previously read Nuget config. The failure used to happen in step 1. while attempting to read a config key which is not available in `gvfs config` file.

Fixes #852

### CODE REVIEW

File: GVFS/GVFS.FunctionalTests/Tools/GVFSProcess.cs [hunk 1]
```diff
@@ -110,7 +110,10 @@ public string RunServiceVerb(string argument)
 
         public string ReadConfig(string key)
         {
-            return this.CallGVFS($"config {key}", failOnError: true).TrimEnd('\r', '\n');
+            // failOnError is set to false because gvfs config read can exit with
+            // GenericError when the key-value is not available in config file. That
+            // is normal.
+            return this.CallGVFS($"config {key}", failOnError: false).TrimEnd('\r', '\n');
```
Comment (wilbaker) [inline GVFS/GVFS.FunctionalTests/Tools/GVFSProcess.cs]: I recommend passing `bool failOnError` in as a parameter like we do for `Prefetch`.  That way the caller is forced to declare whether or not a failure is allowed/expected (it's generally safe to assume that `failOnError: true` is okay, but I don't think we should do that for `failOnError: false`).

File: GVFS/GVFS.FunctionalTests/Tools/GVFSProcess.cs [hunk 2]
```diff
@@ -108,9 +108,12 @@ public string RunServiceVerb(string argument)
...
         }
 
-        public string ReadConfig(string key)
+        public string ReadConfig(string key, bool failOnError)
         {
-            return this.CallGVFS($"config {key}", failOnError: true).TrimEnd('\r', '\n');
+            // failOnError is set to false because gvfs config read can exit with
+            // GenericError when the key-value is not available in config file. That
+            // is normal.
+            return this.CallGVFS($"config {key}", failOnError: failOnError).TrimEnd('\r', '\n');
```
Comment (wilbaker) [inline GVFS/GVFS.FunctionalTests/Tools/GVFSProcess.cs]: Nit: There's no need for `failOnError: ` since we're passing in the named `failOnError` now.

Comment (wilbaker) [reply GVFS/GVFS.FunctionalTests/Tools/GVFSProcess.cs]: Also, this comment:

```
            // failOnError is set to false because gvfs config read can exit with
            // GenericError when the key-value is not available in config file. That
            // is normal.
```

Should be moved to where `ReadConfig` is getting called.
