### PR TITLE
PostFetchJob: Kill running Git process when unmounting

### LINKED ISSUE #409: Issues closing post-fetch job on unmount
We have a variety of things to figure out related to closing the post-fetch job thread in the event of an unmount:

1. We can't abort the thread on Mac. We need a different model to kill the background activity.

2. The ThreadAbort action may not kill the Git process that is running. This could be an existing issue on Windows already.

Things to consider as we investigate these issues: 

* What happens to the post-fetch lock on the shared object cache on thread abort (I'm pretty sure we clean it up on a ThreadAbortException)?

* How can we test that all Git processes are closed as the Mount process closes?

### PR DESCRIPTION
**Pull request by derrickstolee**
The post-fetch job runs up to two Git commands: 'git multi-pack-index write' and 'git commit-graph write'. These can each take up to 30s depending on the amount of work to do. When we unmount, we want to ensure these prcoesses terminate.

Before, we were aborting the post-fetch job thread. This is not cross-platform compliant.

The new approach is to store a `GitProcess` object and pass a Kill signal to that process during unmount. Watch that call for some possible exceptions. Also, add an additional `processLock` to `GitProcess` that holds around our state changes for the process (starting or killing the process) so we don't race by killing a process before it starts and have it start anyway.

As part of revealing this `GitProcess` to the necessary layer, I pulled the implementation of `TryWriteMultiPackIndex` out of the `GitObjects` class.

The test suite was previously exercising this code path during the functional tests, as the functional tests frequently ran faster than the background Git processes. That should give some good data on how this works.

Resolves #409

### CODE REVIEW

File: GVFS/GVFS.Virtualization/FileSystemCallbacks.cs [hunk 1]
```diff
@@ -39,6 +39,7 @@ public class FileSystemCallbacks : IDisposable, IHeartBeatMetadataProvider
         private FileSystemVirtualizer fileSystemVirtualizer;
         private FileProperties logsHeadFileProperties;
         private Thread postFetchJobThread;
+        private GitProcess backgroundGitProcess;
```
Comment (sanoursa) [inline GVFS/GVFS.Virtualization/FileSystemCallbacks.cs]: The word "background" is heavily overloaded in this codebase, so let's find something different. How about `postFetchGitProcess`?

File: GVFS/GVFS.Virtualization/FileSystemCallbacks.cs [hunk 2]
```diff
@@ -584,8 +624,19 @@ private void PostFetchJob(List<string> packIndexes)
...
+                                message: PostFetchTelemetryKey + ": Not launching 'git commit-graph' because the mount is stopping",
+                                keywords: Keywords.Telemetry);
+                            return;
+                        }
+
+                        GitProcess.Result result = this.backgroundGitProcess.WriteCommitGraph(this.context.Enlistment.GitObjectsRoot, packIndexes);
+                        this.backgroundGitProcess = null;
 
                         if (result.HasErrors)
                         {
```
Comment (sanoursa) [inline GVFS/GVFS.Virtualization/FileSystemCallbacks.cs]: I can't put this comment on the correct line but - do we still need the `ThreadAbortException` catch block below?

File: GVFS/GVFS.Virtualization/FileSystemCallbacks.cs [hunk 3]
```diff
@@ -568,12 +590,30 @@ private void PostFetchJob(List<string> packIndexes)
...
+                        {
+                            this.context.Tracer.RelatedWarning(
+                                metadata: null,
+                                message: PostFetchTelemetryKey + ": Not launching 'git multi-pack-index' because the mount is stopping",
+                                keywords: Keywords.Telemetry);
+                            return;
+                        }
+
+                        GitProcess.Result result = this.backgroundGitProcess.WriteMultiPackIndex(this.context.Enlistment.GitObjectsRoot);
+                        this.backgroundGitProcess = null;
```
Comment (sanoursa) [inline GVFS/GVFS.Virtualization/FileSystemCallbacks.cs]: Why are we setting to null here and then constructing a new `GitProcess` again down at line 627? Can we just use the same instance?

File: GVFS/GVFS.Virtualization/FileSystemCallbacks.cs [hunk 4]
```diff
@@ -584,8 +624,19 @@ private void PostFetchJob(List<string> packIndexes)
...
+                                metadata: null,
+                                message: PostFetchTelemetryKey + ": Not launching 'git commit-graph' because the mount is stopping",
+                                keywords: Keywords.Telemetry);
+                            return;
+                        }
+
+                        GitProcess.Result result = this.backgroundGitProcess.WriteCommitGraph(this.context.Enlistment.GitObjectsRoot, packIndexes);
+                        this.backgroundGitProcess = null;
 
                         if (result.HasErrors)
```
Comment (sanoursa) [inline GVFS/GVFS.Virtualization/FileSystemCallbacks.cs]: HasErrors will now be true if we are stopping. It would be good to check that flag when writing the warning message, so we know that this is an expected error from `commit-graph`

File: GVFS/GVFS.Virtualization/FileSystemCallbacks.cs [hunk 5]
```diff
@@ -568,12 +590,30 @@ private void PostFetchJob(List<string> packIndexes)
...
+                        }
+
+                        GitProcess.Result result = this.backgroundGitProcess.WriteMultiPackIndex(this.context.Enlistment.GitObjectsRoot);
+                        this.backgroundGitProcess = null;
+
+                        if (result.HasErrors)
+                        {
+                            this.context.Tracer.RelatedWarning(
+                                metadata: null,
+                                message: PostFetchTelemetryKey + ": Failed to generate multi-pack-index for new packfiles:" + result.Errors,
```
Comment (sanoursa) [inline GVFS/GVFS.Virtualization/FileSystemCallbacks.cs]: Same here, record if we are stopping, so that we can be sure this was expected.

File: GVFS/GVFS.Virtualization/FileSystemCallbacks.cs [hunk 6]
```diff
@@ -197,11 +198,32 @@ public void Stop()
...
+                        }
+                        else
+                        {
+                            this.context.Tracer.RelatedEvent(
+                                EventLevel.Informational,
+                                PostFetchTelemetryKey + ": failed to kill background Git process during " + nameof(this.Stop),
+                                metadata: null);
+                        }
+                    }
+                    catch (NullReferenceException)
```
Comment (sanoursa) [inline GVFS/GVFS.Virtualization/FileSystemCallbacks.cs]: This catch statement is too broad because of the amount of code inside the try block. E.g. we've had bugs before where a tracer object was null, and this would hide that bug.

I think you can pretty easily avoid having to catch `NullReferenceException` here using an interlocked compare/exchange.

File: GVFS/GVFS.Common/Git/GitProcess.cs [hunk 7]
```diff
@@ -108,6 +109,23 @@ public static bool TryGetVersion(string gitBinPath, out GitVersion gitVersion, o
...
+        {
+            try
+            {
+                if (this.executingProcess != null)
+                {
+                    this.executingProcess.Kill();
+                    return true;
+                }
+            }
+            catch (NullReferenceException)
```
Comment (sanoursa) [inline GVFS/GVFS.Common/Git/GitProcess.cs]: Same here, you should be able to drop this if you use an interlocked compare/exchange to set the `executingProcess` to null.

File: GVFS/GVFS.Common/Git/GitProcess.cs [hunk 8]
```diff
@@ -108,6 +109,23 @@ public static bool TryGetVersion(string gitBinPath, out GitVersion gitVersion, o
             return true;
         }
 
+        public bool KillRunningProcess()
```
Comment (sanoursa) [inline GVFS/GVFS.Common/Git/GitProcess.cs]: Naming nit: rename to `TryKillRunningProcess`

File: GVFS/GVFS.Common/Git/GitProcess.cs [hunk 9]
```diff
@@ -108,6 +109,23 @@ public static bool TryGetVersion(string gitBinPath, out GitVersion gitVersion, o
             return true;
         }
 
+        public bool KillRunningProcess()
+        {
+            try
+            {
+                if (this.executingProcess != null)
+                {
+                    this.executingProcess.Kill();
```
Comment (sanoursa) [inline GVFS/GVFS.Common/Git/GitProcess.cs]: What will `Kill` do if the process has already been killed? Will it throw?

File: GVFS/GVFS.Virtualization/FileSystemCallbacks.cs (hunk 6 above)
Comment (derrickstolee) [reply GVFS/GVFS.Virtualization/FileSystemCallbacks.cs]: in this case, we can simply create a local variable and use plain assignment, then refer only to the local copy. A similar pattern can occur in `TryKillRunningProcess()`.

File: GVFS/GVFS.Virtualization/FileSystemCallbacks.cs (hunk 3 above)
Comment (derrickstolee) [reply GVFS/GVFS.Virtualization/FileSystemCallbacks.cs]: We can. The `GitProcess` will handle setting the `Process` it creates to `null` as necessary.

File: GVFS/GVFS.Common/Git/GitProcess.cs (hunk 9 above)
Comment (derrickstolee) [reply GVFS/GVFS.Common/Git/GitProcess.cs]: It will! I'll add the necessary `catch` statements as specified in [the Process.Kill() docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.kill?view=netframework-4.7.2).

File: GVFS/GVFS.Virtualization/FileSystemCallbacks.cs (hunk 5 above)
Comment (derrickstolee) [reply GVFS/GVFS.Virtualization/FileSystemCallbacks.cs]: Oops. I misread this the first time, and you are correct, we should still log this but track the stopping variable.

**Comment by derrickstolee** [comment]
@sanoursa Thanks for the review! I think I've responded to everything.

Here are the things that you probably should take second looks at:

1. `Interlocked.CompareExchange()` didn't seem like the right thing for this application, but I focused on using local variables to avoid nullrefs.

2. I added an extra object lock and `stopping` bool in `GitProcess` to handle changing the inner `Process` state (can't `Start()` or `Kill()` without holding that lock). This prevents a `Kill()` from happening before a `Start()`.

File: GVFS/GVFS.Virtualization/FileSystemCallbacks.cs [hunk 10]
```diff
@@ -568,12 +581,34 @@ private void PostFetchJob(List<string> packIndexes)
...
+                        {
+                            string message = PostFetchTelemetryKey
+                                + ": Failed to generate multi-pack-index for new packfiles"
+                                + (this.stopping ? " (expected because the process is stopping):" : ":")
+                                + result.Errors;
+
+                            this.context.Tracer.RelatedWarning(
+                                metadata: null,
+                                message: message,
+                                keywords: Keywords.Telemetry);
```
Comment (sanoursa) [inline GVFS/GVFS.Virtualization/FileSystemCallbacks.cs]: Do we need this to go to telemetry if it's because of a shutdown? It may make more sense to restrict that to actual midx failures.

File: GVFS/GVFS.Virtualization/FileSystemCallbacks.cs [hunk 11]
```diff
@@ -584,24 +619,33 @@ private void PostFetchJob(List<string> packIndexes)
...
+                        }
 
-                        if (result.HasErrors)
+                        GitProcess.Result result = this.postFetchGitProcess.WriteCommitGraph(this.context.Enlistment.GitObjectsRoot, packIndexes);
+
+                        if (!this.stopping && result.HasErrors)
                         {
+                            string message = PostFetchTelemetryKey
+                                + ": Failed to generate commit-graph for new packfiles"
+                                + (this.stopping ? " (expected because the process is stopping):" : ":")
```
Comment (sanoursa) [inline GVFS/GVFS.Virtualization/FileSystemCallbacks.cs]: We already know `this.stopping` is false here (see line 633), so in this case we do not record a log event or telemetry on shutdown. Whatever the right pattern is, let's make sure the two code paths are consistent with each other.

Comment (derrickstolee) [reply GVFS/GVFS.Virtualization/FileSystemCallbacks.cs]: Oops. I had intended to remove the case from the `if` statement, but if we prefer to not write anything when `stopping`, then I'll leave it in the `if` and remove the tracing.
