### PR TITLE
sparse: check for not recursive matches when finding dirty files

### LINKED ISSUE #1604: 'gvfs sparse' reports files as dirty (incorrectly) when their parent folders are not recursively in the sparse set
This looks like a case that was missed in #1601

Example:

```
F:\testSparse\test\src>gvfs sparse --set ace/bin --prune
Running git status...Failed

git status reported that you have dirty files:

    ace/test.txt

Either commit your changes or reset and clean

Sparse was aborted.
```

In this case `ace/test.txt` is still in the sparse set and so it should not be reported as dirty.

### PR DESCRIPTION
**Pull request by wilbaker**
Resolves #1604

The previous file path matching was only matching against recursive
sparse paths, and incorrectly flagging children of non-recursive folders
as dirty.  This matching has been updated to match both recursive and
non-recursive parents, and unit tests were added to validate the
matching behavior.

### CODE REVIEW

File: GVFS/GVFS/CommandLine/SparseVerb.cs [hunk 1]
```diff
@@ -93,6 +93,44 @@ private enum SetDirectoryTimeResult
...
+            string parentPath = filePath.Substring(startIndex: 0, length: pathSeparatorIndex + 1);
+            if (sparseFolders.Any(x => x.StartsWith(parentPath, GVFSPlatform.Instance.Constants.PathComparison)))
+            {
+                // Path is a child of a non-recursive entry
+                //
+                // Example:
+                //  - Sparse set: A\B\C
+                //  - filePath: A\B\d.txt
+                //
+                // This file is in the sparse set because its parent ("A\B\") is an ancestory of a recursive
```
Comment (wilbaker) [inline GVFS/GVFS/CommandLine/SparseVerb.cs]: `ancestory` -> `ancestor`

File: GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+using NUnit.Framework;
+using System;
+using System.Collections.Generic;
+using System.IO;
+using System.Text;
+
+namespace GVFS.UnitTests.Windows.Windows.CommandLine
+{
+    [TestFixture]
+    public class SparseVerbTests
```
Comment (wilbaker) [inline GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs]: Update functional tests as well?

File: GVFS/GVFS/CommandLine/SparseVerb.cs [hunk 3]
```diff
@@ -93,6 +93,44 @@ private enum SetDirectoryTimeResult
 
         protected override string VerbName => SparseVerbName;
 
+        internal static bool PathCoveredBySparseFolders(ref int index, string statusOutput, HashSet<string> sparseFolders, out string gitPath)
```
Comment (derrickstolee) [inline GVFS/GVFS/CommandLine/SparseVerb.cs]: `internal` :heart:

File: GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+    {
+        // Shorter name for readability
+        private static char dirSep = Path.DirectorySeparatorChar;
```
Comment (kewillford) [inline GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs]: Since this is only Windows why can't we just use a `\`?

File: GVFS/GVFS/CommandLine/SparseVerb.cs [hunk 5]
```diff
@@ -93,6 +93,44 @@ private enum SetDirectoryTimeResult
...
         protected override string VerbName => SparseVerbName;
 
+        internal static bool PathCoveredBySparseFolders(ref int index, string statusOutput, HashSet<string> sparseFolders, out string gitPath)
+        {
+            int endOfPathIndex = statusOutput.IndexOf(StatusPathSeparatorToken, index);
+            gitPath = statusOutput.Substring(index, endOfPathIndex - index);
+            index = endOfPathIndex + 1;
+
+            string filePath = gitPath.Replace(GVFSConstants.GitPathSeparator, Path.DirectorySeparatorChar);
+            if (sparseFolders.Any(x => filePath.StartsWith(x + Path.DirectorySeparatorChar, GVFSPlatform.Instance.Constants.PathComparison)))
```
Comment (derrickstolee) [inline GVFS/GVFS/CommandLine/SparseVerb.cs]: Since `sparseFolders` is a `HashSet<string>` you are probably better off stripping parents from `filePath` and checking `sparseFolders.Contains(filePath)`. [Here is similar code in the `git sparse-checkout` implementation](https://github.com/derrickstolee/git/blob/7577ffc034be90bd60da17e8f3189d999e7f8149/dir.c#L731-L756).

File: GVFS/GVFS/CommandLine/SparseVerb.cs [hunk 6]
```diff
@@ -93,6 +93,44 @@ private enum SetDirectoryTimeResult
...
+            int pathSeparatorIndex = filePath.LastIndexOf(Path.DirectorySeparatorChar);
+            if (pathSeparatorIndex < 0)
+            {
+                // Path is in the root, and root entries are always in the sparse set
+                return true;
+            }
+
+            // Get the parent path (including the path separator)
+            string parentPath = filePath.Substring(startIndex: 0, length: pathSeparatorIndex + 1);
+            if (sparseFolders.Any(x => x.StartsWith(parentPath, GVFSPlatform.Instance.Constants.PathComparison)))
```
Comment (derrickstolee) [inline GVFS/GVFS/CommandLine/SparseVerb.cs]: This has a less-obvious perf change, but creating a `HashSet<string>` full of the "parent paths" (i.e. those that are parents of the sparse folders, but not actually in the sparse folders) we can test `parentFolders.Contains(parentPath)`. [Here is the equivalent Git code](https://github.com/derrickstolee/git/blob/7577ffc034be90bd60da17e8f3189d999e7f8149/dir.c#L631-L717), but the sparse-checkout file already has the full list of parent paths as part of the list, so it may not be incredibly helpful.

The only reason I bring this up is because the current algorithm is quadratic: O(N*M) where N is the number of sparse folders and M is the number of dirty paths. Using the `HashSet<string>` method I describe will be O(N+M*d) (where d is the max depth of a dirty path) because O(N) time to construct the hash sets and O(M*d) time to check the values.

File: GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs [hunk 7]
```diff
@@ -0,0 +1,114 @@
...
+
+        [TestCase]
+        public void PathCoveredBySparseFolders_RootPaths()
+        {
+            string rootPaths = $"a.txt{SparseVerb.StatusPathSeparatorToken}b.txt{SparseVerb.StatusPathSeparatorToken}c.txt{SparseVerb.StatusPathSeparatorToken}";
```
Comment (kewillford) [inline GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs]: I think that you are using `SparseVerb.StatusPathSeparatorToken` so that if it changes it won't break the tests but I would argue that the tests should __not__ use internal information and should break.  So my suggestion is to have
```
private const char StatusPathSeparatorToken = '\0';
```
in the test.  It will only be one place to change but tests will break when the internals of the SparseVerb change.

File: GVFS/GVFS/CommandLine/SparseVerb.cs [hunk 8]
```diff
@@ -93,6 +93,44 @@ private enum SetDirectoryTimeResult
 
         protected override string VerbName => SparseVerbName;
 
+        internal static bool PathCoveredBySparseFolders(ref int index, string statusOutput, HashSet<string> sparseFolders, out string gitPath)
+        {
+            int endOfPathIndex = statusOutput.IndexOf(StatusPathSeparatorToken, index);
+            gitPath = statusOutput.Substring(index, endOfPathIndex - index);
+            index = endOfPathIndex + 1;
```
Comment (kewillford) [inline GVFS/GVFS/CommandLine/SparseVerb.cs]: Just thinking here and wondering if it would make the tests easier and more specific if we pulled this out into something like:
```
private static string GetNextGitPath(ref int index, string statusOutput)
{
    int endOfPathIndex = statusOutput.IndexOf(StatusPathSeparatorToken, index);
    gitPath = statusOutput.Substring(index, endOfPathIndex - index);
    index = endOfPathIndex + 1;
    return gitPath;
}
```
Then this method could just be 
```
internal static bool PathCoveredBySparseFolders(string gitPath, HashSet<string> sparseFolders)
```
`GetPathsNotCoveredBySparseFolders` would need to change to something like
```
string gitPath = GetNextGitPath(ref index, statusOutput);
if (!PathCoveredBySparseFolders(gitPath, sparseFolders))
{
...
```
Then the tests wouldn't need to be testing the parsing of the status output although it would be good to have some coverage there as well.  So I think after writing this I am more on the fence.

File: GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs [hunk 9]
```diff
@@ -0,0 +1,114 @@
...
+
+            ConfirmAllPathsCovered(rootPaths, new HashSet<string>());
+            ConfirmAllPathsCovered(rootPaths, new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "A" });
+            ConfirmAllPathsCovered(rootPaths, new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "A", $"B{dirSep}C" });
```
Comment (kewillford) [inline GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs]: Maybe have some static `HashSet`s for these?

File: GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs (hunk 4 above)
Comment (wilbaker) [reply GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs]: We could do that, and I will make the change.

I went back and forth on the best way to set these up.  The trouble is these tests aren't really *Windows* specific, but they depend on the `GVFS.Windows` project (which is Windows specific).

I will update these to use `\`, and if we decide to make the test cross-plat at some point we can move the code into a .NET Standard assembly or update `GVFS.Windows` to be .NET Core (assuming ProjFS is by that point).

File: GVFS/GVFS/CommandLine/SparseVerb.cs (hunk 6 above)
Comment (wilbaker) [reply GVFS/GVFS/CommandLine/SparseVerb.cs]: Thanks for the great perf suggestions.  I think I will file a follow up for these so that those changes can be isolated as a performance only PR.

Comment (wilbaker) [reply GVFS/GVFS/CommandLine/SparseVerb.cs]: Filed #1608

File: GVFS/GVFS/CommandLine/SparseVerb.cs (hunk 5 above)
Comment (wilbaker) [reply GVFS/GVFS/CommandLine/SparseVerb.cs]: Filed follow-up #1608 to address this.

File: GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs (hunk 9 above)
Comment (wilbaker) [reply GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs]: I will give that a try and use them where it improves readability.

File: GVFS/GVFS/CommandLine/SparseVerb.cs (hunk 8 above)
Comment (wilbaker) [reply GVFS/GVFS/CommandLine/SparseVerb.cs]: I like this suggestion, thanks!  I will update `SparseVerb` and add tests for `GetNextGitPath`.

File: GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs [hunk 10]
```diff
@@ -0,0 +1,119 @@
...
+            rootPaths.Append($"A/B/B.txt{StatusPathSeparatorToken}");
+            rootPaths.Append($"A/C.txt{StatusPathSeparatorToken}");
+            rootPaths.Append($"A/D/E/C.txt{StatusPathSeparatorToken}");
+
+            ConfirmAllPathsCovered(
+                rootPaths.ToString(),
+                new HashSet<string>(StringComparer.OrdinalIgnoreCase)
+                {
+                    $"A\\B\\C\\D",
+                    $"A\\D\\E\\F\\G"
```
Comment (kewillford) [inline GVFS/GVFS.UnitTests.Windows/Windows/CommandLine/SparseVerbTests.cs]: We can get rid of `$` now and use `@`
```
@"A\B\C\D",
@"A\D\E\F\G"
```

File: GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/SparseTests.cs [hunk 11]
```diff
@@ -455,23 +455,31 @@ public void ModifiedFileOldSparseSetShouldNotAllowSparseFolderRemove()
...
+            string additionalSparseFolder = Path.Combine("GVFS", "GVFS.Tests", "Should");
+            this.gvfsProcess.AddSparseFolders(this.mainSparseFolder, additionalSparseFolder);
+            this.ValidateFoldersInSparseList(this.mainSparseFolder, additionalSparseFolder);
 
             // Ensure that folderToCreateFileIn is on disk so that there's something to prune
             string folderToCreateFileIn = Path.Combine("GVFS", "GVFS.Common");
-            this.gvfsProcess.AddSparseFolders(this.mainSparseFolder, folderToCreateFileIn);
-            this.ValidateFoldersInSparseList(this.mainSparseFolder, folderToCreateFileIn);
+            this.gvfsProcess.AddSparseFolders(this.mainSparseFolder, additionalSparseFolder, folderToCreateFileIn);
+            this.ValidateFoldersInSparseList(this.mainSparseFolder, additionalSparseFolder, folderToCreateFileIn);
```
Comment (wilbaker) [inline GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/SparseTests.cs]: This change is needed on line 488 as well

**Comment by wilbaker** [comment]
Next commit will address @kewillford's comment here:

https://github.com/microsoft/VFSForGit/pull/1607#discussion_r350968841
